# This kubexit image is not publicly available
FROM ghcr.io/inigo4562/kubexit:0.3.3 AS kubexit

FROM gcr.io/cloudsql-docker/gce-proxy:1.31.2 AS runner

COPY --from=kubexit /bin/kubexit /bin/

ENTRYPOINT ["kubexit", "/cloud_sql_proxy"]
